import { lz, type Exercise } from '@/core/domain';

/**
 * Exercise library. Add new exercises here – workouts reference them by id.
 * MET values are approximations based on the Compendium of Physical
 * Activities (resistance training 3.5–6, vigorous calisthenics 8, burpees ~8+).
 */
export const EXERCISES: readonly Exercise[] = [
  // ---- Lower body -------------------------------------------------------
  {
    id: 'squat',
    name: lz('Knäböj', 'Squat'),
    cue: lz('Bröstet upp, knäna utåt.', 'Chest up, knees out.'),
    category: 'strength',
    equipment: ['none'],
    muscles: { quads: 1, glutes: 0.8, hamstrings: 0.4, core: 0.3 },
    met: 5.0,
    secondsPerRep: 3,
  },
  {
    id: 'lunge',
    name: lz('Utfall', 'Lunge'),
    cue: lz('Långt steg, sänk rakt ner.', 'Long step, drop straight down.'),
    category: 'strength',
    equipment: ['none'],
    muscles: { quads: 0.9, glutes: 0.9, hamstrings: 0.5, core: 0.3 },
    met: 5.0,
    secondsPerRep: 3,
  },
  {
    id: 'glute-bridge',
    name: lz('Höftlyft', 'Glute bridge'),
    cue: lz('Kläm ihop rumpan i toppen.', 'Squeeze the glutes at the top.'),
    category: 'strength',
    equipment: ['none'],
    muscles: { glutes: 1, hamstrings: 0.6, core: 0.2 },
    met: 3.5,
    secondsPerRep: 2.5,
  },
  {
    id: 'goblet-squat',
    name: lz('Goblet-knäböj', 'Goblet squat'),
    cue: lz('Håll vikten nära bröstet.', 'Keep the weight close to your chest.'),
    category: 'strength',
    equipment: ['dumbbells', 'kettlebell'],
    muscles: { quads: 1, glutes: 0.8, core: 0.5, back: 0.2 },
    met: 6.0,
    secondsPerRep: 3.5,
  },
  {
    id: 'romanian-deadlift',
    name: lz('Rumänska marklyft', 'Romanian deadlift'),
    cue: lz('Skjut höften bakåt, rak rygg.', 'Push the hips back, flat back.'),
    category: 'strength',
    equipment: ['dumbbells', 'barbell'],
    muscles: { hamstrings: 1, glutes: 0.9, back: 0.5, core: 0.3 },
    met: 6.0,
    secondsPerRep: 3.5,
  },
  {
    id: 'calf-raise',
    name: lz('Tåhävningar', 'Calf raise'),
    category: 'strength',
    equipment: ['none'],
    muscles: { calves: 1 },
    met: 3.0,
    secondsPerRep: 2,
  },
  {
    id: 'wall-sit',
    name: lz('Jägarvila', 'Wall sit'),
    cue: lz('Lår parallella med golvet.', 'Thighs parallel to the floor.'),
    category: 'strength',
    equipment: ['none'],
    muscles: { quads: 1, glutes: 0.4 },
    met: 4.0,
    secondsPerRep: 1,
  },

  // ---- Upper body -------------------------------------------------------
  {
    id: 'push-up',
    name: lz('Armhävningar', 'Push-up'),
    cue: lz('Rak kropp, armbågarna nära.', 'Straight body, elbows tucked.'),
    category: 'strength',
    equipment: ['none'],
    muscles: { chest: 1, triceps: 0.7, shoulders: 0.5, core: 0.4 },
    met: 5.5,
    secondsPerRep: 2.5,
  },
  {
    id: 'shoulder-press',
    name: lz('Axelpress', 'Shoulder press'),
    cue: lz('Spänn magen, pressa rakt upp.', 'Brace the core, press straight up.'),
    category: 'strength',
    equipment: ['dumbbells'],
    muscles: { shoulders: 1, triceps: 0.6, core: 0.2 },
    met: 5.0,
    secondsPerRep: 3,
  },
  {
    id: 'bent-over-row',
    name: lz('Hantelrodd', 'Bent-over row'),
    cue: lz('Dra armbågarna bakåt mot höften.', 'Drive the elbows back toward the hips.'),
    category: 'strength',
    equipment: ['dumbbells'],
    muscles: { back: 1, biceps: 0.6, shoulders: 0.3, core: 0.3 },
    met: 5.0,
    secondsPerRep: 3,
  },
  {
    id: 'bicep-curl',
    name: lz('Bicepscurl', 'Bicep curl'),
    category: 'strength',
    equipment: ['dumbbells'],
    muscles: { biceps: 1 },
    met: 3.5,
    secondsPerRep: 3,
  },
  {
    id: 'tricep-dip',
    name: lz('Dips på bänk', 'Bench dip'),
    cue: lz('Armbågarna rakt bakåt.', 'Elbows straight back.'),
    category: 'strength',
    equipment: ['bench'],
    muscles: { triceps: 1, chest: 0.4, shoulders: 0.4 },
    met: 4.5,
    secondsPerRep: 2.5,
  },
  {
    id: 'pull-up',
    name: lz('Chins', 'Pull-up'),
    cue: lz('Hakan över stången.', 'Chin over the bar.'),
    category: 'strength',
    equipment: ['pullUpBar'],
    muscles: { back: 1, biceps: 0.8, core: 0.3 },
    met: 8.0,
    secondsPerRep: 3.5,
  },

  // ---- Core -------------------------------------------------------------
  {
    id: 'plank',
    name: lz('Planka', 'Plank'),
    cue: lz('Rak linje från huvud till häl.', 'Straight line from head to heel.'),
    category: 'core',
    equipment: ['none'],
    muscles: { core: 1, shoulders: 0.3 },
    met: 3.5,
    secondsPerRep: 1,
  },
  {
    id: 'crunch',
    name: lz('Situps', 'Crunch'),
    category: 'core',
    equipment: ['none'],
    muscles: { core: 1 },
    met: 3.8,
    secondsPerRep: 2,
  },
  {
    id: 'russian-twist',
    name: lz('Ryska vridningar', 'Russian twist'),
    category: 'core',
    equipment: ['none'],
    muscles: { core: 1 },
    met: 4.0,
    secondsPerRep: 1.5,
  },
  {
    id: 'leg-raise',
    name: lz('Benlyft', 'Leg raise'),
    cue: lz('Pressa ländryggen mot golvet.', 'Press your lower back into the floor.'),
    category: 'core',
    equipment: ['none'],
    muscles: { core: 1 },
    met: 4.0,
    secondsPerRep: 3,
  },
  {
    id: 'side-plank',
    name: lz('Sidoplanka', 'Side plank'),
    category: 'core',
    equipment: ['none'],
    muscles: { core: 1, shoulders: 0.3 },
    met: 3.5,
    secondsPerRep: 1,
  },

  // ---- Cardio / full body ----------------------------------------------
  {
    id: 'burpee',
    name: lz('Burpees', 'Burpee'),
    cue: lz('Explosivt upp, mjukt ner.', 'Explode up, land soft.'),
    category: 'cardio',
    equipment: ['none'],
    muscles: { fullBody: 1, quads: 0.6, chest: 0.5, core: 0.5, shoulders: 0.4 },
    met: 8.0,
    secondsPerRep: 4,
  },
  {
    id: 'mountain-climber',
    name: lz('Mountain climbers', 'Mountain climbers'),
    category: 'cardio',
    equipment: ['none'],
    muscles: { core: 0.9, quads: 0.5, shoulders: 0.5, fullBody: 0.6 },
    met: 8.0,
    secondsPerRep: 1,
  },
  {
    id: 'jumping-jack',
    name: lz('Sprattelgubbe', 'Jumping jacks'),
    category: 'cardio',
    equipment: ['none'],
    muscles: { fullBody: 1, calves: 0.5, shoulders: 0.4 },
    met: 7.0,
    secondsPerRep: 1,
  },
  {
    id: 'high-knees',
    name: lz('Höga knän', 'High knees'),
    category: 'cardio',
    equipment: ['none'],
    muscles: { fullBody: 0.8, quads: 0.6, core: 0.5, calves: 0.4 },
    met: 8.0,
    secondsPerRep: 1,
  },
  {
    id: 'jump-squat',
    name: lz('Upphopp', 'Jump squat'),
    cue: lz('Landa mjukt, direkt ner igen.', 'Land soft, straight back down.'),
    category: 'cardio',
    equipment: ['none'],
    muscles: { quads: 1, glutes: 0.8, calves: 0.6, fullBody: 0.5 },
    met: 8.0,
    secondsPerRep: 2,
  },
  {
    id: 'kettlebell-swing',
    name: lz('Kettlebellsving', 'Kettlebell swing'),
    cue: lz('Kraften kommer från höften.', 'The power comes from the hips.'),
    category: 'cardio',
    equipment: ['kettlebell'],
    muscles: { glutes: 1, hamstrings: 0.8, back: 0.5, core: 0.5, shoulders: 0.3 },
    met: 9.0,
    secondsPerRep: 1.5,
  },

  // ---- Mobility ---------------------------------------------------------
  {
    id: 'arm-circles',
    name: lz('Armcirklar', 'Arm circles'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { shoulders: 0.6 },
    met: 2.5,
    secondsPerRep: 1,
  },
  {
    id: 'hip-circles',
    name: lz('Höftcirklar', 'Hip circles'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { glutes: 0.3, core: 0.3 },
    met: 2.5,
    secondsPerRep: 1,
  },
  {
    id: 'cat-cow',
    name: lz('Katt-ko', 'Cat-cow'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { back: 0.4, core: 0.3 },
    met: 2.3,
    secondsPerRep: 1,
  },
  {
    id: 'hamstring-stretch',
    name: lz('Baksida lår-stretch', 'Hamstring stretch'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { hamstrings: 0.3 },
    met: 2.3,
    secondsPerRep: 1,
  },
  {
    id: 'child-pose',
    name: lz('Barnets position', 'Child’s pose'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { back: 0.3 },
    met: 2.0,
    secondsPerRep: 1,
  },
  {
    id: 'quad-stretch',
    name: lz('Framsida lår-stretch', 'Quad stretch'),
    category: 'mobility',
    equipment: ['none'],
    muscles: { quads: 0.3 },
    met: 2.3,
    secondsPerRep: 1,
  },
];

const EXERCISE_MAP: ReadonlyMap<string, Exercise> = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return EXERCISE_MAP.get(id);
}
