import { lz, type Workout } from '@/core/domain';
import {
  BODYWEIGHT_FULL,
  COOLDOWN_STRETCH,
  CORE_CRUSHER,
  FINISHER_BURN,
  HIIT_CIRCUIT,
  KETTLEBELL_ENGINE,
  LOWER_BODY_STRENGTH,
  MOBILITY_FLOW,
  UPPER_BODY_STRENGTH,
  WARMUP_DYNAMIC,
  WARMUP_SHORT,
} from './blocks';
import {
  BLASTER_CIRCUIT,
  CALIS_CIRCUIT,
  COOLDOWN_LITE,
  CORE_DESTROYER_ABC,
  DB3_FULLBODY_A,
  DB5_PUSH,
  DEADLIFT_MAIN,
  FATDESTROYER_UPPER_A,
  ICF5X5_A,
  KB_CORE_CIRCUIT,
  MSSF_WORKOUT_A,
  MASS10_CHEST,
  PHUL_UPPER_POWER,
  PPL_PUSH_A,
  PMB_CHEST_TRICEPS,
  SEAL_CONDITIONING,
  SQUAT_HEAVY_DAY,
  STARR5X5_POWER,
  TACTICAL_STRENGTH,
  TOTAL_PACKAGE_D1,
  WARMUP_LIFTING,
  WOMENS_LEGS_GLUTES,
} from './programBlocks';

/**
 * The workout library. Every program is an ordered list of reusable blocks.
 * To add a program: compose blocks, give it metadata, done.
 */
export const WORKOUTS: readonly Workout[] = [
  {
    id: 'full-body-blast',
    title: lz('Full Body Blast', 'Full Body Blast'),
    tagline: lz('Hela kroppen. Ingen utrustning.', 'Whole body. No equipment.'),
    description: lz(
      'Ett komplett helkroppspass med enbart kroppsvikt. Perfekt hemma eller på resande fot.',
      'A complete full-body session using only your bodyweight. Perfect at home or on the road.',
    ),
    goal: 'endurance',
    difficulty: 'beginner',
    equipment: ['none'],
    primaryMuscles: ['quads', 'chest', 'glutes', 'core'],
    blocks: [WARMUP_DYNAMIC, BODYWEIGHT_FULL, COOLDOWN_STRETCH],
    estimatedMinutes: 28,
    accent: 'red',
  },
  {
    id: 'lower-power',
    title: lz('Lower Power', 'Lower Power'),
    tagline: lz('Benstyrka som märks.', 'Leg strength you can feel.'),
    description: lz(
      'Tunga underkroppsövningar med hantlar eller kettlebell. Fokus på knäböj och höftgångjärn.',
      'Heavy lower-body work with dumbbells or a kettlebell. Focus on squat and hip hinge patterns.',
    ),
    goal: 'strength',
    difficulty: 'intermediate',
    equipment: ['dumbbells', 'kettlebell'],
    primaryMuscles: ['quads', 'glutes', 'hamstrings'],
    blocks: [WARMUP_DYNAMIC, LOWER_BODY_STRENGTH, COOLDOWN_STRETCH],
    estimatedMinutes: 38,
    accent: 'orange',
  },
  {
    id: 'upper-armour',
    title: lz('Upper Armour', 'Upper Armour'),
    tagline: lz('Bröst, rygg, axlar, armar.', 'Chest, back, shoulders, arms.'),
    description: lz(
      'Klassisk överkroppsdag med hantlar och bänk. Bygg en stark och balanserad överkropp.',
      'Classic upper-body day with dumbbells and a bench. Build a strong, balanced upper body.',
    ),
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    equipment: ['dumbbells', 'bench'],
    primaryMuscles: ['chest', 'back', 'shoulders', 'biceps', 'triceps'],
    blocks: [WARMUP_SHORT, UPPER_BODY_STRENGTH, COOLDOWN_STRETCH],
    estimatedMinutes: 40,
    accent: 'violet',
  },
  {
    id: 'hiit-inferno',
    title: lz('HIIT Inferno', 'HIIT Inferno'),
    tagline: lz('20 minuter. Maxpuls.', '20 minutes. Max heart rate.'),
    description: lz(
      'Tre varv explosiv intervallträning följt av en brutal finisher. Kort, hårt, effektivt.',
      'Three rounds of explosive intervals followed by a brutal finisher. Short, hard, effective.',
    ),
    goal: 'fatLoss',
    difficulty: 'advanced',
    equipment: ['none'],
    primaryMuscles: ['fullBody', 'quads', 'core'],
    blocks: [WARMUP_SHORT, HIIT_CIRCUIT, FINISHER_BURN, COOLDOWN_STRETCH],
    estimatedMinutes: 22,
    accent: 'magenta',
  },
  {
    id: 'core-crusher',
    title: lz('Core Crusher', 'Core Crusher'),
    tagline: lz('Stålmage på 15 minuter.', 'Abs of steel in 15 minutes.'),
    description: lz(
      'Två varv riktad bålträning. Passar som fristående pass eller som tillägg efter cardio.',
      'Two rounds of targeted core work. Works standalone or as an add-on after cardio.',
    ),
    goal: 'strength',
    difficulty: 'beginner',
    equipment: ['none'],
    primaryMuscles: ['core'],
    blocks: [WARMUP_SHORT, CORE_CRUSHER],
    estimatedMinutes: 15,
    accent: 'yellow',
  },
  {
    id: 'kettlebell-engine',
    title: lz('Kettlebell Engine', 'Kettlebell Engine'),
    tagline: lz('En kula. Fyra varv. Allt.', 'One bell. Four rounds. Everything.'),
    description: lz(
      'Kraft och kondition i ett. Swing, goblet squat och armhävningar i fyra intensiva varv.',
      'Power and conditioning in one. Swings, goblet squats and push-ups across four intense rounds.',
    ),
    goal: 'endurance',
    difficulty: 'intermediate',
    equipment: ['kettlebell'],
    primaryMuscles: ['glutes', 'hamstrings', 'quads', 'chest'],
    blocks: [WARMUP_DYNAMIC, KETTLEBELL_ENGINE, COOLDOWN_STRETCH],
    estimatedMinutes: 30,
    accent: 'cyan',
  },
  {
    id: 'mobility-reset',
    title: lz('Mobility Reset', 'Mobility Reset'),
    tagline: lz('Återhämta. Rör dig fritt.', 'Recover. Move freely.'),
    description: lz(
      'Lugnt rörlighetsflöde för vilodagar eller efter hårda pass. Ingen puls, bara rörelse.',
      'A calm mobility flow for rest days or after hard sessions. No heart rate, just movement.',
    ),
    goal: 'mobility',
    difficulty: 'beginner',
    equipment: ['none'],
    primaryMuscles: ['back', 'hamstrings', 'glutes'],
    blocks: [MOBILITY_FLOW],
    estimatedMinutes: 12,
    accent: 'lime',
  },

  /* ---------------------------------------------------------------------- */
  /* Programs sourced from the Muscle & Strength workout routine database.  */
  /* Each entry is one representative session of the full program; the      */
  /* schedule lives in the description.                                      */
  /* ---------------------------------------------------------------------- */

  {
    id: 'icf-5x5-strength',
    title: lz('Ice Cream Fitness 5×5', 'Ice Cream Fitness 5×5'),
    tagline: lz('Nybörjarkraft, tre pass i veckan.', 'Novice strength, three days a week.'),
    description: lz(
      'Jason Blahas klassiska 5×5-program från Muscle & Strength: 12 veckor, tre pass per vecka som alternerar A/B med linjär viktprogression. Vila 3–5 min på femmorna och 1–2 min på tilläggen. Denna session är Workout A (Workout B byter in 1×5 marklyft och stående press).',
      'Jason Blaha’s classic 5×5 program from Muscle & Strength: 12 weeks, alternating workouts A and B three days a week with linear progression. Rest 3–5 min on the 5s, 1–2 min on accessories. This session is Workout A (Workout B swaps in a 1×5 deadlift and standing press).',
    ),
    goal: 'strength',
    difficulty: 'beginner',
    equipment: ['barbell', 'bench'],
    primaryMuscles: ['quads', 'chest', 'back', 'triceps'],
    blocks: [WARMUP_LIFTING, ICF5X5_A, COOLDOWN_LITE],
    estimatedMinutes: 85,
    accent: 'red',
  },
  {
    id: 'bill-starr-5x5',
    title: lz('Bill Starr 5×5', 'Bill Starr 5×5'),
    tagline: lz('Beprövad linjär kraft.', 'Old-school linear strength.'),
    description: lz(
      'Bill Starrs 5×5 för medelavancerade (Muscle & Strength): 12 veckor, tre pass – måndag kraft 5×5, onsdag volym 4×5 och fredag toppar till tunga triplar. Denna session är måndagens kraftpass med assistans för svank och mage.',
      'Bill Starr’s intermediate 5×5 (via Muscle & Strength): 12 weeks, three sessions – Monday power 5×5, Wednesday volume 4×5 and Friday heavy triples. This session is the Monday power day with lower-back and ab assistance.',
    ),
    goal: 'strength',
    difficulty: 'intermediate',
    equipment: ['barbell'],
    primaryMuscles: ['quads', 'chest', 'back'],
    blocks: [WARMUP_LIFTING, STARR5X5_POWER, COOLDOWN_LITE],
    estimatedMinutes: 70,
    accent: 'orange',
  },
  {
    id: 'phul-upper-power',
    title: lz('P.H.U.L. – Upper Power', 'P.H.U.L. – Upper Power'),
    tagline: lz('Kraft och muskelmassa, 4 dagar/vecka.', 'Strength and size, 4 days a week.'),
    description: lz(
      'Power Hypertrophy Upper Lower är M&S mest hämtade 4-dagarsprogram (12 veckor): över-/underkropp x kraft + hypertrofi. Denna session är Day 1 – Upper Power. Lat pulldown i originalet är bytt mot chins; vila 2–3 min före de tunga lyften.',
      'Power Hypertrophy Upper Lower is M&S’s most downloaded 4-day program (12 weeks): upper/lower power and hypertrophy days. This session is Day 1 – Upper Power; the original’s lat pulldown is swapped for chin-ups. Rest 2–3 min before the heavy lifts.',
    ),
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'bench', 'pullUpBar'],
    primaryMuscles: ['chest', 'back', 'shoulders', 'biceps', 'triceps'],
    blocks: [WARMUP_SHORT, PHUL_UPPER_POWER, COOLDOWN_LITE],
    estimatedMinutes: 50,
    accent: 'violet',
  },
  {
    id: 'ms-full-body-a',
    title: lz('M&S Full Body – A', 'M&S Full Body – A'),
    tagline: lz(
      'Tre pass. Alla muskler. 20-reps-knäböj.',
      'Three sessions. All muscles. 20-rep squats.',
    ),
    description: lz(
      'Muscle & Strengths massprogram för nybörjare (12 veckor, måndag, onsdag & fredag med rampade 5×5 och 2 min vila). Denna session är Workout A; fredagens Workout C avslutas med en 20-reps-set på knäböj.',
      'M&S mass builder for beginners (12 weeks, Mon/Wed/Fri with ramped 5×5 and 2-min rests). This session is Workout A; Friday’s Workout C finishes with a single 20-rep squat set.',
    ),
    goal: 'hypertrophy',
    difficulty: 'beginner',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['quads', 'chest', 'back', 'hamstrings'],
    blocks: [WARMUP_LIFTING, MSSF_WORKOUT_A, COOLDOWN_LITE],
    estimatedMinutes: 60,
    accent: 'cyan',
  },
  {
    id: 'total-package-d1',
    title: lz('The Total Package – Dag 1', 'The Total Package – Day 1'),
    tagline: lz('5×5 för styrka, 4×10 för massa.', '5×5 for strength, 4×10 for size.'),
    description: lz(
      'Total Package (Muscle & Strength, 8 veckor, 3 dagar/vecka) varvar ett tungt 5×5-huvudlyft med 4×10-hypertrofi för hela kroppen. Denna session är Dag 1; kabelrodden är bytt mot hantelrodd och benpressen mot knäböj + utfall.',
      'The Total Package (Muscle & Strength, 8 weeks, 3 days a week) pairs one heavy 5×5 lift with 4×10 hypertrophy work for the whole body. This session is Day 1; cable rows become dumbbell rows and the leg press is replaced by squat + lunge volume.',
    ),
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['quads', 'chest', 'back', 'shoulders'],
    blocks: [WARMUP_LIFTING, TOTAL_PACKAGE_D1, COOLDOWN_LITE],
    estimatedMinutes: 70,
    accent: 'yellow',
  },
  {
    id: 'pmb-chest-triceps',
    title: lz('Power Muscle Burn – Bröst & Tris', 'Power Muscle Burn – Chest & Tri'),
    tagline: lz(
      'Kraft-set, muskel-set, bränn-set. 40 reps.',
      'Power sets, muscle sets, 40-rep burn sets.',
    ),
    description: lz(
      'Steve Shaws 5-dagars powerbuilding-program på Muscle & Strength (12 veckor). Varje muskelgrupp får 2–4 kraft-set à 3–5 reps, muskel-set à 6–12 och ett bränn-set med totalt 40 reps via korta pauser. Denna session är Dag 1 – bröst & triceps.',
      'Steve Shaw’s 5-day powerbuilding program on Muscle & Strength (12 weeks). Every muscle group gets 2–4 power sets of 3–5, muscle sets of 6–12 and one 40-rep burn set done rest-pause. This session is Day 1 – chest & triceps.',
    ),
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['chest', 'triceps', 'shoulders'],
    blocks: [WARMUP_SHORT, PMB_CHEST_TRICEPS, COOLDOWN_LITE],
    estimatedMinutes: 50,
    accent: 'magenta',
  },
  {
    id: 'ppl-push-a',
    title: lz('6-Dagars PPL – Push A', '6-Day PPL – Push A'),
    tagline: lz('Rep goals: 15, 25 och 50.', 'Rep goals: 15, 25 and 50.'),
    description: lz(
      'Det högvolymsiga 6-dagars push/pull/legs-programmet på Muscle & Strength (12 veckor) styrs av totala repmål: 5 set à 15 totalt på huvudlyftet (plus en back-off-set vid 80 %), 25–30 reps på medelövningarna och 5×50 med bara 15–30 sek vila som avslutning. Denna session är Push A – bröst, axlar & triceps.',
      'The high-volume 6-day push/pull/legs program on Muscle & Strength (12 weeks) is driven by total rep goals: 5×15 on the main lift (plus an 80 % back-off set), 3×25–30 and 5×50 on accessories. This session is Push A – chest, shoulders & triceps; keep rests at 30–60 s on the fast sets.',
    ),
    goal: 'hypertrophy',
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['chest', 'shoulders', 'triceps'],
    blocks: [WARMUP_SHORT, PPL_PUSH_A, COOLDOWN_LITE],
    estimatedMinutes: 45,
    accent: 'red',
  },
  {
    id: 'mass10-chest',
    title: lz('10-veckors massa – Bröst', '10-Week Mass – Chest'),
    tagline: lz('Pyramid: 10, 8, 8, 6.', 'Pyramid: 10, 8, 8, 6.'),
    description: lz(
      'M&S-program för hardgainern: 10 veckor, fyra dagar, varje muskelgrupp en gång i veckan med tunga basövningar och pyramidset (10/8/8/6, tyngre för varje set). Denna session är Måndag – bröst & triceps; veckan fortsätter med rygg/biceps, axlar/underarmar och ben.',
      'The M&S hardgainer classic: 10 weeks, four days, each muscle group once a week with heavy compounds and pyramid sets (10/8/8/6, adding weight each set). This session is Monday – chest & triceps.',
    ),
    goal: 'hypertrophy',
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['chest', 'triceps'],
    blocks: [WARMUP_LIFTING, MASS10_CHEST, COOLDOWN_LITE],
    estimatedMinutes: 50,
    accent: 'orange',
  },
  {
    id: 'dumbbell5-push',
    title: lz('Hantel-5:an – Push', 'Dumbbell 5-Day – Push'),
    tagline: lz('Bara hantlar. Fem dagar.', 'Dumbbells only. Five days.'),
    description: lz(
      'M&S hantelprogram (12 veckor, 5 dagar): push, ben/core, pull, ben/core och en hel-overkroppsdag. Denna session är Dag 1 – bröst, axlar & triceps med 8–12 reps och 45–90 sek vila. Golvpressen i originalet körs här som armhävningar.',
      'The M&S dumbbell program (12 weeks, 5 days): push, legs/core, pull, legs/core and a full-upper-body day. This session is Day 1 – chest, shoulders & triceps for 8–12 reps, resting 45–90 s. The original’s floor press becomes push-ups here.',
    ),
    goal: 'hypertrophy',
    difficulty: 'intermediate',
    equipment: ['dumbbells', 'bench'],
    primaryMuscles: ['chest', 'shoulders', 'triceps'],
    blocks: [WARMUP_SHORT, DB5_PUSH, COOLDOWN_LITE],
    estimatedMinutes: 45,
    accent: 'violet',
  },
  {
    id: 'dumbbell3-fullbody-a',
    title: lz('Hantel Full Body – Dag 1', 'Dumbbell Full Body – Day 1'),
    tagline: lz('Ett par hantlar räcker.', 'One pair of dumbbells does it.'),
    description: lz(
      'Perfekt hemma eller på resan: M&S 3-dagars hantelsprogram (8 veckor) med lagom volym för muskeltillväxt – tre set à 8–10 reps, två à 8. Denna session är Dag 1; bench-isoleringarna ligger på Dag 2 och 3.',
      'Home- and travel-friendly: the M&S 3-day dumbbell program (8 weeks) with just enough volume for growth – three sets of 8–10, two of 8. This session is Day 1; the other days rotate the isolation work.',
    ),
    goal: 'hypertrophy',
    difficulty: 'beginner',
    equipment: ['dumbbells', 'bench'],
    primaryMuscles: ['quads', 'hamstrings', 'back', 'chest'],
    blocks: [WARMUP_SHORT, DB3_FULLBODY_A, COOLDOWN_LITE],
    estimatedMinutes: 38,
    accent: 'cyan',
  },
  {
    id: 'squat-heavy-day',
    title: lz('Complete Squat – Tunga dagen', 'Complete Squat – Heavy Day'),
    tagline: lz('75–90 % i 8 veckor. Nytt 1RM.', '75–90 % for 8 weeks. New 1RM.'),
    description: lz(
      'The Complete Squat Program på Muscle & Strength: 8 veckor, 4 pass/vecka med en tung knäböjsdag (75–90 % 1RM, 3 min vila), en explosiv speed-dag och två helkroppspass. Denna session är den tunga dagen; knäböjet toppas enligt veckogrammet mot nya max.',
      'The Complete Squat Program on Muscle & Strength: 8 weeks, 4 sessions a week – one heavy squat day (75–90 % 1RM, 3-min rests), one dynamic speed day and two full-body days. This session is the heavy day; work up to the weekly top set on squats.',
    ),
    goal: 'strength',
    difficulty: 'beginner',
    equipment: ['barbell', 'dumbbells', 'pullUpBar'],
    primaryMuscles: ['quads', 'glutes', 'hamstrings', 'back'],
    blocks: [WARMUP_LIFTING, SQUAT_HEAVY_DAY, COOLDOWN_STRETCH],
    estimatedMinutes: 55,
    accent: 'lime',
  },
  {
    id: 'deadlift-spec-a',
    title: lz('Deadlift-Specialisering – A', 'Deadlift Specialization – A'),
    tagline: lz('Marklyft tre gånger i veckan.', 'Deadlift three times a week.'),
    description: lz(
      'M&S 8-veckorsprogram för maximal styrka i marklyften: tre marklyfts-dagar (tungt, speed respektive defizit/paus) och två överkroppsdagar, alla under 60 min. Denna session är tunga dag A med 2–3 min vila; veckogrammet bygger mot nytt 1RM på vecka 8.',
      'The M&S 8-week max-strength plan: three deadlift days (heavy, speed and deficit/pause) plus two upper-body days, all under 60 minutes. This session is heavy Day A with 2–3 min rests; the weekly chart builds to a new 1RM by week 8.',
    ),
    goal: 'strength',
    difficulty: 'advanced',
    equipment: ['barbell', 'dumbbells'],
    primaryMuscles: ['hamstrings', 'glutes', 'back', 'quads'],
    blocks: [WARMUP_LIFTING, DEADLIFT_MAIN, COOLDOWN_STRETCH],
    estimatedMinutes: 35,
    accent: 'red',
  },
  {
    id: 'navy-seal-conditioning',
    title: lz('Navy SEAL – Kondition', 'Navy SEAL – Conditioning'),
    tagline: lz('Kroppsvikt, sprintar, löpning.', 'Bodyweight, sprints, running.'),
    description: lz(
      'Sex-veckorsprogrammet från Muscle & Strength bygger funktionell styrka, snabbhet och uthållighet i fem pass/vecka (speed, power, strength, hypertrofi och ett konditionspass). Denna session är konditionscirkeln – kör den 2 varv och avsluta med 3–5 km jogg i lugnt tempo.',
      'The 6-week plan from Muscle & Strength builds functional strength, speed and endurance across five weekly sessions (power, strength, hypertrophy and conditioning). This session is the conditioning circuit – run 2 rounds, then finish with a 3–5 km steady jog.',
    ),
    goal: 'endurance',
    difficulty: 'advanced',
    equipment: ['none', 'pullUpBar'],
    primaryMuscles: ['fullBody', 'quads', 'core', 'back'],
    blocks: [WARMUP_DYNAMIC, SEAL_CONDITIONING],
    estimatedMinutes: 35,
    accent: 'cyan',
  },
  {
    id: 'tactical-strength',
    title: lz('Tactical Physique – Styrka', 'Tactical Physique – Strength'),
    tagline: lz('Lyft tungt. Spring fort.', 'Lift heavy. Run fast.'),
    description: lz(
      'The Tactical Physique på Muscle & Strength kombinerar funktionell styrka, supersets och kondition. Denna session är veckans styrkepass: knäböj och rumänska i 4×5, superset-armhävningar/chins efteråt, core och avslutande 8×20 sek sprintintervaller.',
      'The Tactical Physique on Muscle & Strength blends functional strength, supersets and conditioning. This session is the weekly strength day: squats and RDLs for 4×5, push-up/pull-up superset work, core, and 8×20 s sprint intervals to finish.',
    ),
    goal: 'strength',
    difficulty: 'intermediate',
    equipment: ['barbell', 'dumbbells', 'pullUpBar'],
    primaryMuscles: ['quads', 'hamstrings', 'back', 'chest', 'core'],
    blocks: [WARMUP_DYNAMIC, TACTICAL_STRENGTH, COOLDOWN_STRETCH],
    estimatedMinutes: 60,
    accent: 'magenta',
  },
  {
    id: 'calis-100-circuit',
    title: lz('Calisthenics 100', 'Calisthenics 100'),
    tagline: lz('100 reps per varv. Ingen utrustning.', '100 reps a round. No equipment.'),
    description: lz(
      'Calisthenics for Lifters på Muscle & Strength (12 veckor, 2 pass/vecka, 25–35 min): det ena passet är enorma set på tid, det andra är denna cirkel med 10 övningar à 10 reps utan vila mellan. Börja med fyra varv – sikta på fem till sex.',
      'Calisthenics for Lifters on Muscle & Strength (12 weeks, 2 sessions a week, 25–35 min): one workout is timed giant sets, the other is this 10-exercise × 10-rep circuit with no rest between moves. Start at 4 rounds, aim for 8.',
    ),
    goal: 'fatLoss',
    difficulty: 'beginner',
    equipment: ['none', 'dumbbells'],
    primaryMuscles: ['fullBody', 'chest', 'core', 'quads'],
    blocks: [WARMUP_DYNAMIC, CALIS_CIRCUIT],
    estimatedMinutes: 25,
    accent: 'yellow',
  },
  {
    id: 'body-blaster-circuit',
    title: lz('Body Blaster – Circuit', 'Body Blaster – Circuit'),
    tagline: lz('Fetförbränning utan utrustning.', 'Fat loss with zero equipment.'),
    description: lz(
      'Body Blaster (Muscle & Strength, 6 veckor, 3 pass/vecka) varvar EMOM-varv och cirklar med sprintar, burpees, hoppluck och skuggboxning. Denna session är cirkeldagen: 5 varv, cirka 25 minuter, 2 min vila efter sista övningen på varje varv.',
      'Body Blaster (Muscle & Strength, 6 weeks, 3 days a week) alternates EMOM and circuit sessions with sprints, burpees, jump squats and shadow boxing. This session is the circuit day: 5 rounds, around 25 minutes, resting 2 min after each round.',
    ),
    goal: 'fatLoss',
    difficulty: 'beginner',
    equipment: ['none'],
    primaryMuscles: ['fullBody', 'quads', 'core', 'chest'],
    blocks: [WARMUP_DYNAMIC, BLASTER_CIRCUIT],
    estimatedMinutes: 28,
    accent: 'orange',
  },
  {
    id: 'fat-destroyer-upper-a',
    title: lz('Fat Destroyer – Upper A', 'Fat Destroyer – Upper A'),
    tagline: lz('Fetförbränning. Behåll musklerna.', 'Burn fat. Keep the muscle.'),
    description: lz(
      '12 Week Fat Destroyer är M&S kompletta program för att bli av med fett: lyft 4 dagar/vecka (upper/lower A & B) plus kost- och kardioplan. Denna session är Upper A – håll samma vikt varje set, lägg på när 8–10 känns lätt och kör 20–30 min cardio efteråt.',
      'The 12 Week Fat Destroyer is M&S’s complete fat-loss plan: lift four days a week (upper/lower A & B) plus a diet and cardio schedule. This session is Upper A – use the same weight every set, add when 8–10 feels easy, and finish with 20–30 min of cardio.',
    ),
    goal: 'fatLoss',
    difficulty: 'beginner',
    equipment: ['barbell', 'dumbbells', 'pullUpBar', 'bench'],
    primaryMuscles: ['chest', 'back', 'shoulders', 'biceps', 'triceps'],
    blocks: [WARMUP_SHORT, FATDESTROYER_UPPER_A, COOLDOWN_LITE],
    estimatedMinutes: 40,
    accent: 'yellow',
  },
  {
    id: 'core-destroyer-abc',
    title: lz('Core Destroyer – ABC', 'Core Destroyer – ABC'),
    tagline: lz('Ab Blasting Circuit på 10 min.', 'A 10-minute Ab Blasting Circuit.'),
    description: lz(
      'Core Destroyer (Muscle & Strength, 8 veckor, 2 pass/vecka) har en raka-set-session och denna Ab Blasting Circuit: fem magövningar på tid, back-to-back, 3 varv med 2 min vila mellan. Kör den efter ett mindre styrkepass eller ensam.',
      'The Core Destroyer (Muscle & Strength, 8 weeks, 2 days a week) pairs a straight-set session with this Ab Blasting Circuit: five timed core moves done back-to-back for 3 rounds with 2-min breaks. Use it after an arm/shoulder session or on its own.',
    ),
    goal: 'strength',
    difficulty: 'beginner',
    equipment: ['none', 'dumbbells'],
    primaryMuscles: ['core'],
    blocks: [CORE_DESTROYER_ABC],
    estimatedMinutes: 12,
    accent: 'violet',
  },
  {
    id: 'kb-core-circuit',
    title: lz('KB Core Circuit', 'KB Core Circuit'),
    tagline: lz('En kula. Hela core.', 'One bell. A complete core.'),
    description: lz(
      '4 Week Complete Kettlebell Ab & Core från Muscle & Strength: fyra veckor, tre pass i veckan, ett kettlebell – rörelser i tre plan, från stående till liggande. Denna session är hela cirkeln – 8 övningar, 4 varv, ca 10 reps per sida, så lite vila som möjligt.',
      'The 4 Week Complete Kettlebell Ab & Core from Muscle & Strength: one bell, all three planes of motion, standing to floor. This session is the full circuit – 8 movements, 4 rounds, roughly 10 reps a side with minimal rest.',
    ),
    goal: 'endurance',
    difficulty: 'beginner',
    equipment: ['kettlebell'],
    primaryMuscles: ['core', 'glutes', 'shoulders', 'back'],
    blocks: [WARMUP_DYNAMIC, KB_CORE_CIRCUIT, COOLDOWN_LITE],
    estimatedMinutes: 28,
    accent: 'cyan',
  },
  {
    id: 'womens-legs-glutes',
    title: lz('Women’s 12 – Ben & Rumpa', 'Women’s 12 – Legs & Glutes'),
    tagline: lz(
      'Måndag: knäböj, thrust, steg upp – plus HIIT.',
      'Monday: squats, thrusts, steps. + HIIT.',
    ),
    description: lz(
      'M&S 12-veckorsprogram för kvinnor (5 styrkepass i veckan med upplagd cardio): måndag ben & säte, tisdag rygg/ar mar, onsdag ben, torsdag bröst/axlar, fredag ben/ar mar. Denna session är måndagen – kör 15 min HIIT på cykel efteråt som i originalet.',
      'The M&S 12-week women’s program (5 lifting days with scheduled cardio): Mon legs & glutes, Tue back & arms, Wed legs, Thu chest & shoulders, Fri legs & arms. This session is Monday – finish with 15 min of bike HIIT as written.',
    ),
    goal: 'hypertrophy',
    difficulty: 'beginner',
    equipment: ['barbell', 'dumbbells', 'bench'],
    primaryMuscles: ['quads', 'glutes', 'hamstrings', 'calves'],
    blocks: [WARMUP_DYNAMIC, WOMENS_LEGS_GLUTES, COOLDOWN_STRETCH],
    estimatedMinutes: 45,
    accent: 'magenta',
  },
];

export function getWorkout(id: string): Workout | undefined {
  return WORKOUTS.find((w) => w.id === id);
}
